USE [Velera] ;
GO
SELECT
    [i].[IntegrationRuntime]
  , [i].[Type]
  , [i].[DependencyType]
  , [i].[DependencyName]
FROM [ADF].[IntegrationRunTimes] AS [i] ;

SELECT
    [l].[LinkedService]
  , [l].[Type]
  , [l].[ConnectViaReferenceName]
  , [l].[ConnectViaType]
  , [l].[Parameters]
  , [l].[Annotations]
  , [l].[TypeProperties]
  , [l].[Value]
FROM [ADF].[LinkedServices] AS [l] 
WHERE type LIKE 'Snowflake%';

SELECT
    [s].[DataflowName]
  , [s].[StepType]
  , [s].[StepOrder]
  , [s].[StepName]
  , [s].[DatasetReference]
  , [s].[DatasetType]
  , [s].[LinkedServiceName]
  , [s].[FolderName]
  , [s].[TargetLocation]
  , [ds].[Dataset]
  , [ds].[DatasetType]
  , [ds].[LinkedService]
  , [ds].[Folder]
  --, [ds].[Description]
  , [ds].[Schema]
  , [ds].[Parameters]
  --, [ds].[Annotations]
  , [ds].[TypeProperties]
  , [ds].[TargetTable]
  , [ds].[TargetSchema]
  , [ds].[FileLocation]
  , [ds].[FolderPath]
  , [ds].[FileName]
FROM [ADF].[DataFlowSteps] [s]
LEFT JOIN [ADF].[DataSets] AS [ds] ON [s].[DatasetReference] = [ds].[Dataset]
WHERE [s].[DataflowName] IN( SELECT [s].[DataflowName]
                             FROM [ADF].[DataFlowSteps] [s]
                             WHERE [s].[LinkedServiceName] IN ('LS_SF_Application_DB', 'LS_SF_CONSOLIDATE', 'snowflake', 'SnowflakeDev')) ;

SELECT
    [ca].[PipelineName]
  , [ca].[ActivityName]
  , [ca].[typeProperties.logSettings.logLocationSettings.linkedServiceName.referenceName]
  , [ca].[typeProperties.logSettings.logLocationSettings.linkedServiceName.type]
  , [ca].[PipelineName]
  , [ca].[ActivityName]
  , [ca].[dependsOn]
  , [ca].[description]
  , [ca].[inputs]
  , [ca].[name]
  , [ca].[outputs]
  , [ca].[policy.retry]
  , [ca].[policy.retryIntervalInSeconds]
  , [ca].[policy.secureInput]
  , [ca].[policy.secureOutput]
  , [ca].[policy.timeout]
  , [ca].[type]
  , [ca].[typeProperties.dataIntegrationUnits]
  , [ca].[typeProperties.enableSkipIncompatibleRow]
  , [ca].[typeProperties.enableStaging]
  , [ca].[typeProperties.logSettings.copyActivityLogSettings.enableReliableLogging]
  , [ca].[typeProperties.logSettings.copyActivityLogSettings.logLevel]
  , [ca].[typeProperties.logSettings.enableCopyActivityLog]
  , [ca].[typeProperties.logSettings.logLocationSettings.linkedServiceName.referenceName]
  , [ca].[typeProperties.logSettings.logLocationSettings.linkedServiceName.type]
  , [ca].[typeProperties.logSettings.logLocationSettings.path]
  , [ca].[typeProperties.logStorageSettings.linkedServiceName.referenceName]
  , [ca].[typeProperties.logStorageSettings.linkedServiceName.type]
  , [ca].[typeProperties.logStorageSettings.path.type]
  , [ca].[typeProperties.logStorageSettings.path.value]
  , [ca].[typeProperties.parallelCopies]
  , [ca].[typeProperties.sink.allowCopyCommand]
  , [ca].[typeProperties.sink.allowPolyBase]
  , [ca].[typeProperties.sink.disableMetricsCollection]
  , [ca].[typeProperties.sink.formatSettings.fileExtension]
  , [ca].[typeProperties.sink.formatSettings.quoteAllText]
  , [ca].[typeProperties.sink.formatSettings.type]
  , [ca].[typeProperties.sink.importSettings.additionalCopyOptions.FORCE]
  , [ca].[typeProperties.sink.importSettings.additionalCopyOptions.ON_ERROR]
  , [ca].[typeProperties.sink.importSettings.type]
  , [ca].[typeProperties.sink.polyBaseSettings.rejectType]
  , [ca].[typeProperties.sink.polyBaseSettings.rejectValue]
  , [ca].[typeProperties.sink.polyBaseSettings.useTypeDefault]
  , [ca].[typeProperties.sink.preCopyScript]
  , [ca].[typeProperties.sink.preCopyScript.type]
  , [ca].[typeProperties.sink.preCopyScript.value]
  , [ca].[typeProperties.sink.sqlWriterUseTableLock]
  , [ca].[typeProperties.sink.storeSettings.copyBehavior]
  , [ca].[typeProperties.sink.storeSettings.type]
  , [ca].[typeProperties.sink.tableOption]
  , [ca].[typeProperties.sink.type]
  , [ca].[typeProperties.sink.writeBatchSize]
  , [ca].[typeProperties.sink.writeBehavior]
  , [ca].[typeProperties.source.additionalColumns]
  , [ca].[typeProperties.source.exportSettings.type]
  , [ca].[typeProperties.source.formatSettings.compressionProperties.preserveZipFileNameAsFolder]
  , [ca].[typeProperties.source.formatSettings.compressionProperties.type]
  , [ca].[typeProperties.source.formatSettings.skipLineCount]
  , [ca].[typeProperties.source.formatSettings.type]
  , [ca].[typeProperties.source.isolationLevel]
  , [ca].[typeProperties.source.partitionOption]
  , [ca].[typeProperties.source.query]
  , [ca].[typeProperties.source.query.type]
  , [ca].[typeProperties.source.query.value]
  , [ca].[typeProperties.source.queryTimeout]
  , [ca].[typeProperties.source.sqlReaderQuery]
  , [ca].[typeProperties.source.sqlReaderQuery.type]
  , [ca].[typeProperties.source.sqlReaderQuery.value]
  , [ca].[typeProperties.source.sqlReaderStoredProcedureName]
  , [ca].[typeProperties.source.storeSettings.deleteFilesAfterCompletion]
  , [ca].[typeProperties.source.storeSettings.enablePartitionDiscovery]
  , [ca].[typeProperties.source.storeSettings.recursive]
  , [ca].[typeProperties.source.storeSettings.type]
  , [ca].[typeProperties.source.storeSettings.wildcardFileName]
  , [ca].[typeProperties.source.storeSettings.wildcardFolderPath.type]
  , [ca].[typeProperties.source.storeSettings.wildcardFolderPath.value]
  , [ca].[typeProperties.source.storedProcedureParameters.CreateDate.type]
  , [ca].[typeProperties.source.storedProcedureParameters.CreateDate.value.type]
  , [ca].[typeProperties.source.storedProcedureParameters.CreateDate.value.value]
  , [ca].[typeProperties.source.storedProcedureParameters.reportDate.type]
  , [ca].[typeProperties.source.storedProcedureParameters.reportDate.value.type]
  , [ca].[typeProperties.source.storedProcedureParameters.reportDate.value.value]
  , [ca].[typeProperties.source.storedProcedureParameters.settlementDate.type]
  , [ca].[typeProperties.source.storedProcedureParameters.settlementDate.value.type]
  , [ca].[typeProperties.source.storedProcedureParameters.settlementDate.value.value]
  , [ca].[typeProperties.source.type]
  , [ca].[typeProperties.stagingSettings.enableCompression]
  , [ca].[typeProperties.stagingSettings.linkedServiceName.referenceName]
  , [ca].[typeProperties.stagingSettings.linkedServiceName.type]
  , [ca].[typeProperties.stagingSettings.path]
  , [ca].[typeProperties.translator.mappings]
  , [ca].[typeProperties.translator.type]
  , [ca].[typeProperties.translator.typeConversion]
  , [ca].[typeProperties.translator.typeConversionSettings.allowDataTruncation]
  , [ca].[typeProperties.translator.typeConversionSettings.treatBooleanAsNumber]
  , [ca].[typeProperties.validateDataConsistency]
  , [ca].[userProperties]
  , [ip2].[parameters] AS [InputParameters]
  , [ip2].[referenceName] AS [InputReferenceName]
  , [ip2].[type] AS [InputType]
  , [ids].[DatasetType] AS [InputDatasetType]
  , [ids].[LinkedService] AS [InputLinkedService]
  , [ids].[Folder] AS [InputFolder]
  , [ids].[Description] AS [InputDescription]
  , [ids].[Schema] AS [InputSchema]
  , [ids].[Parameters] AS [InputParameters]
  , [ids].[Annotations] AS [InputAnnotations]
  , [ids].[TypeProperties] AS [InputTypeProperties]
  , [ids].[TargetTable] AS [InputTargetTable]
  , [ids].[TargetSchema] AS [InputTargetSchema]
  , [ids].[FileLocation] AS [InputFileLocation]
  , [ids].[FolderPath] AS [InputFolderPath]
  , [ids].[FileName] AS [InputFileName]
  , [op2].[parameters] AS [OutputParameters]
  , [op2].[referenceName] AS [OutputReferenceName]
  , [op2].[type] AS [OutputType]
  , [ods].[Dataset] AS [OutputDataset]
  , [ods].[DatasetType] AS [OutputDatasetType]
  , [ods].[LinkedService] AS [OutputLinkedService]
  , [ods].[Folder] AS [OutputFolder]
  , [ods].[Description] AS [OutputDescription]
  , [ods].[Schema] AS [OutputSchema]
  , [ods].[Parameters] AS [OutputParameters]
  , [ods].[Annotations] AS [OutputAnnotations]
  , [ods].[TypeProperties] AS [OutputTypeProperties]
  , [ods].[TargetTable] AS [OutputTargetTable]
  , [ods].[TargetSchema] AS [OutputTargetSchema]
  , [ods].[FileLocation] AS [OutputFileLocation]
  , [ods].[FolderPath] AS [OutputFolderPath]
  , [ods].[FileName] AS [OutputFileName]
FROM [ADF].[CopyActivities] [ca]
OUTER APPLY OPENJSON([ca].[outputs]) [op]
OUTER APPLY OPENJSON([op].[value])
            WITH( [parameters] VARCHAR(MAX), [referenceName] VARCHAR(128), [type] VARCHAR(128)) AS [op2]
OUTER APPLY OPENJSON([ca].[inputs]) [ip]
OUTER APPLY OPENJSON([ip].[value])
            WITH( [parameters] VARCHAR(MAX), [referenceName] VARCHAR(128), [type] VARCHAR(128)) AS [ip2]
LEFT JOIN [ADF].[DataSets] AS [ids] ON [ip2].[referenceName] = [ids].[Dataset]
LEFT JOIN [ADF].[DataSets] AS [ods] ON [op2].[referenceName] = [ods].[Dataset] ;




SELECT
    [ds].[Dataset]
  , [ds].[DatasetType]
  , [ds].[LinkedService]
  , [ds].[Folder]
  , [ds].[Description]
  , [ds].[Schema]
  , [ds].[Parameters]
  , [ds].[Annotations]
  , [ds].[TypeProperties]
  , [ds].[TargetTable]
  , [ds].[TargetSchema]
  , [ds].[FileLocation]
  , [ds].[FolderPath]
  , [ds].[FileName]
FROM [ADF].[DataSets] AS [ds] ;

SELECT
    [dd].[DataFlow]
  , [dd].[Type]
  , [dd].[DependencyType]
  , [dd].[DependencyName]
FROM [ADF].[DataFlowDependencies] AS [dd] ;

SELECT
    [p].[Pipeline]
  , [p].[PipelineActivityCnt]
  , [p].[ParameterCnt]
  , [p].[ParameterWithValueCnt]
  , [p].[DependsOnCnt]
FROM [ADF].[PipeLines] AS [p] ;

SELECT
    [p].[Pipeline]
  , [p].[PipelineActivitiesCnt]
  , [p].[Level]
  , [p].[ChildrenCnt]
  , [p].[ParentId]
  , [p].[Id]
  , [p].[Activity]
  , [p].[ActivityType]
  , [p].[ParentActivity]
  , [p].[ParentActivityType]
  , [p].[SwitchExpressionValue]
  , [p].[SwitchExpressionType]
  , [p].[IFExpressionValue]
  , [p].[IFExpressionType]
  , [p].[SwitchValue]
  , [p].[IFCondition]
FROM [ADF].[PipeLineActivities] AS [p] ;

SELECT
    [p].[Pipeline]
  , [p].[ActivityName]
  , [p].[ActivityType]
  , [p].[Level]
  , [p].[ActivityId]
  , [p].[ActivityValue]
FROM [ADF].[PipeLineAllActivities] AS [p] ;

SELECT
    [t].[Pipeline]
  , [t].[Activity]
  , [t].[ActivityType]
  , [t].[QueryId]
  , [t].[Query]
  , [t].[Type]
FROM [ADF].[SQLQueries] AS [t] ;

SELECT
    [q].[Pipeline]
  , [q].[Activity]
  , [q].[ActivityType]
  , [q].[ActivityId]
  , [q].[Query]
FROM [ADF].[ActivityQueries] AS [q] ;

SELECT
    [pd].[Pipeline]
  , [pd].[DependsOnType]
  , [pd].[DependsOnName]
FROM [ADF].[PipeLineDependencies] AS [pd] ;

SELECT
    [t].[TriggerName]
  , [t].[RunTimeState]
  , [t].[PipeLineCnt]
  , [t].[PipeLines]
  , [t].[TriggerType]
  , [t].[Frequency]
  , [t].[Interval]
  , [t].[StartTime]
  , [t].[TimeZone]
FROM [ADF].[Triggers] AS [t] ;

SELECT
    [tt].[TriggerName]
  , [tt].[RunTimeState]
  , [tt].[ScheduleTimeCnt]
  , [tt].[ScheduleTimeId]
  , [tt].[TriggerType]
  , [tt].[Frequency]
  , [tt].[Interval]
  , [tt].[StartTime]
  , [tt].[TimeZone]
  , [tt].[ScheduleTime]
FROM [ADF].[TriggerTimes] AS [tt] ;

SELECT
    [tp].[TriggerName]
  , [tp].[RunTimeState]
  , [tp].[ParameterCnt]
  , [tp].[ParameterName]
  , [tp].[ParameterType]
  , [tp].[ParameterDefaultValue]
FROM [ADF].[TriggerParameters] AS [tp] ;

SELECT
    [tpl].[TriggerName]
  , [tpl].[RunTimeState]
  , [tpl].[PipeLineCnt]
  , [tpl].[PipeLine]
FROM [ADF].[TriggerPipeLines] AS [tpl] ;

SELECT
    [t].[Pipeline]
  , [t].[StoredProcedureName]
  , [t].[StoredProcedureId]
  , [t].[ActivityTypeList]
  , [t].[StoredProcedureCnt]
  , [t].[StoredProcedureParamCnt]
  , [t].[StoredProcedureParamNotNullCnt]
FROM [ADF].[StoredProcedureOrLookup] AS [t] ;

SELECT
    [t].[Pipeline]
  , [t].[Activity]
  , [t].[ActivityType]
  , [t].[StoredProcedureName]
  , [t].[StoredProcedureId]
  , [t].[StoredProcedureParamId]
  , [t].[ParameterName]
  , [t].[ParameterDataType]
  , [t].[ParameterType]
  , [t].[ParameterValue]
FROM [ADF].[StoredProcedureOrLookupParameters] AS [t] ;

SELECT
    [a].[Pipeline]
  , [a].[ActivityName]
  , [a].[Level]
  , [a].[ActivityType]
  , [a].[InputOrOutput]
  , [a].[InputOutputId]
  , [a].[ReferenceName]
  , [a].[ReferenceType]
  , [a].[LinkedService]
  , [a].[ReferenceValue]
FROM [ADF].[ActivityReferences] AS [a]
ORDER BY [a].[Pipeline]
       , [a].[ActivityName]
       , [a].[InputOrOutput]
       , [a].[InputOutputId] ;
