USE [Velera] ;
GO
SELECT
    [i].[IntegrationRuntime]
  , [i].[Type]
  , [i].[DependencyType]
  , [i].[DependencyName]
FROM [ADF].[IntegrationRunTimes] AS [i] ;

SELECT
    [l].[LinkedService]
  , [l].[Type]
  , [l].[ConnectViaReferenceName]
  , [l].[ConnectViaType]
  , [l].[Parameters]
  , [l].[Annotations]
  , [l].[TypeProperties]
  , [l].[Value]
FROM [ADF].[LinkedServices] AS [l]
WHERE [l].[Type] LIKE 'Snowflake%' ;

SELECT
    CASE WHEN [s].[DataflowName] IN( SELECT [s].[DataflowName] FROM [ADF].[DataFlowSteps] AS [s] WHERE [s].[LinkedServiceName] IN ('LS_SF_Application_DB', 'LS_SF_CONSOLIDATE', 'snowflake', 'SnowflakeDev')) THEN 'Yes' ELSE 'No' END AS [IsDestinationSnowflake]
  , [pa].[Pipeline]
  , [s].[DataflowName]
  , [td].[TriggerName]
  , [td].[TriggerType]
  , [td].[RuntimeState] AS [TriggerRuntimeState]
  , [td].[Frequency] AS [TriggerFrequency]
  , [td].[StartTime] AS [TriggerStartTime]
  , [td].[TimeZone] AS [TriggerTimeZone]
  , [s].[StepType]
  , [s].[StepOrder]
  , [s].[StepName]
  , [s].[DatasetReference]
  , [s].[DatasetType]
  , [s].[LinkedServiceName]
  , [s].[FolderName]
  , [s].[TargetLocation]
  , [ds].[TargetTable]
  , [ds].[TargetSchema]
  , [ds].[FileLocation]
  , [ds].[FolderPath]
  , [ds].[FileName]
  , [ds].[Dataset]
  , [ds].[DatasetType]
  , [ds].[LinkedService]
  , [ds].[Folder]
  --, [ds].[Description]
  , [ds].[Schema]
  , [ds].[Parameters]
  --, [ds].[Annotations]
  , [ds].[TypeProperties]
FROM [ADF].[DataFlowSteps] AS [s]
LEFT JOIN [ADF].[DataSets] AS [ds] ON [s].[DatasetReference] = [ds].[Dataset]
LEFT JOIN [ADF].[PipeLineActivities] AS [pa] ON [pa].[ActivityType] = 'ExecuteDataFlow' AND [pa].[Activity] = [s].[DataflowName]
LEFT JOIN [ADF].[TriggersDetailed] AS [td] ON [td].[PipelineName] = [pa].[Pipeline]
--WHERE [s].[DataflowName] IN( SELECT [s].[DataflowName]
--                             FROM [ADF].[DataFlowSteps] [s]
--                             WHERE [s].[LinkedServiceName] IN ('LS_SF_Application_DB', 'LS_SF_CONSOLIDATE', 'snowflake', 'SnowflakeDev'))
ORDER BY 1 DESC
       , [s].[DataflowName]
       , [pa].[Pipeline]
       , [td].[TriggerName] ;

DROP TABLE IF EXISTS [##CopyActivities] ;

SELECT
    CASE WHEN [ods].[LinkedService] IN ('LS_SF_Application_DB', 'LS_SF_CONSOLIDATE', 'snowflake', 'SnowflakeDev') THEN 'Yes' ELSE 'No' END AS [IsDestinationSnowflake]
  , [ca].[PipelineName]
  , [ca].[ActivityName] AS [CopyActivityName]
  , [td].[TriggerName]
  , [td].[TriggerType]
  , [td].[RuntimeState] AS [TriggerRuntimeState]
  , [td].[Frequency] AS [TriggerFrequency]
  , [td].[StartTime] AS [TriggerStartTime]
  , [td].[TimeZone] AS [TriggerTimeZone]
  , [ca].[dependsOn]
  , [ca].[description]
  , [ca].[inputs]
  , [ca].[name]
  , [ca].[outputs]
  , [ca].[policy.retry]
  , [ca].[policy.retryIntervalInSeconds]
  , [ca].[policy.secureInput]
  , [ca].[policy.secureOutput]
  , [ca].[policy.timeout]
  , [ca].[type]
  , [ca].[typeProperties.dataIntegrationUnits]
  , [ca].[typeProperties.enableSkipIncompatibleRow]
  , [ca].[typeProperties.enableStaging]
  , [ca].[typeProperties.logSettings.copyActivityLogSettings.enableReliableLogging]
  , [ca].[typeProperties.logSettings.copyActivityLogSettings.logLevel]
  , [ca].[typeProperties.logSettings.enableCopyActivityLog]
  , [ca].[typeProperties.logSettings.logLocationSettings.linkedServiceName.referenceName]
  , [ca].[typeProperties.logSettings.logLocationSettings.linkedServiceName.type]
  , [ca].[typeProperties.logSettings.logLocationSettings.path]
  , [ca].[typeProperties.logStorageSettings.linkedServiceName.referenceName]
  , [ca].[typeProperties.logStorageSettings.linkedServiceName.type]
  , [ca].[typeProperties.logStorageSettings.path.type]
  , [ca].[typeProperties.logStorageSettings.path.value]
  , [ca].[typeProperties.parallelCopies]
  , [ca].[typeProperties.sink.allowCopyCommand]
  , [ca].[typeProperties.sink.allowPolyBase]
  , [ca].[typeProperties.sink.disableMetricsCollection]
  , [ca].[typeProperties.sink.formatSettings.fileExtension]
  , [ca].[typeProperties.sink.formatSettings.quoteAllText]
  , [ca].[typeProperties.sink.formatSettings.type]
  , [ca].[typeProperties.sink.importSettings.additionalCopyOptions.FORCE]
  , [ca].[typeProperties.sink.importSettings.additionalCopyOptions.ON_ERROR]
  , [ca].[typeProperties.sink.importSettings.type]
  , [ca].[typeProperties.sink.polyBaseSettings.rejectType]
  , [ca].[typeProperties.sink.polyBaseSettings.rejectValue]
  , [ca].[typeProperties.sink.polyBaseSettings.useTypeDefault]
  , [ca].[typeProperties.sink.preCopyScript]
  , [ca].[typeProperties.sink.preCopyScript.type]
  , [ca].[typeProperties.sink.preCopyScript.value]
  , [ca].[typeProperties.sink.sqlWriterUseTableLock]
  , [ca].[typeProperties.sink.storeSettings.copyBehavior]
  , [ca].[typeProperties.sink.storeSettings.type]
  , [ca].[typeProperties.sink.tableOption]
  , [ca].[typeProperties.sink.type]
  , [ca].[typeProperties.sink.writeBatchSize]
  , [ca].[typeProperties.sink.writeBehavior]
  , [ca].[typeProperties.source.additionalColumns]
  , [ca].[typeProperties.source.exportSettings.type]
  , [ca].[typeProperties.source.formatSettings.compressionProperties.preserveZipFileNameAsFolder]
  , [ca].[typeProperties.source.formatSettings.compressionProperties.type]
  , [ca].[typeProperties.source.formatSettings.skipLineCount]
  , [ca].[typeProperties.source.formatSettings.type]
  , [ca].[typeProperties.source.isolationLevel]
  , [ca].[typeProperties.source.partitionOption]
  , [ca].[typeProperties.source.query]
  , [ca].[typeProperties.source.query.type]
  , [ca].[typeProperties.source.query.value]
  , [ca].[typeProperties.source.queryTimeout]
  , [ca].[typeProperties.source.sqlReaderQuery]
  , [ca].[typeProperties.source.sqlReaderQuery.type]
  , [ca].[typeProperties.source.sqlReaderQuery.value]
  , [ca].[typeProperties.source.sqlReaderStoredProcedureName]
  , [ca].[typeProperties.source.storeSettings.deleteFilesAfterCompletion]
  , [ca].[typeProperties.source.storeSettings.enablePartitionDiscovery]
  , [ca].[typeProperties.source.storeSettings.recursive]
  , [ca].[typeProperties.source.storeSettings.type]
  , [ca].[typeProperties.source.storeSettings.wildcardFileName]
  , [ca].[typeProperties.source.storeSettings.wildcardFolderPath.type]
  , [ca].[typeProperties.source.storeSettings.wildcardFolderPath.value]
  , [ca].[typeProperties.source.storedProcedureParameters.CreateDate.type]
  , [ca].[typeProperties.source.storedProcedureParameters.CreateDate.value.type]
  , [ca].[typeProperties.source.storedProcedureParameters.CreateDate.value.value]
  , [ca].[typeProperties.source.storedProcedureParameters.reportDate.type]
  , [ca].[typeProperties.source.storedProcedureParameters.reportDate.value.type]
  , [ca].[typeProperties.source.storedProcedureParameters.reportDate.value.value]
  , [ca].[typeProperties.source.storedProcedureParameters.settlementDate.type]
  , [ca].[typeProperties.source.storedProcedureParameters.settlementDate.value.type]
  , [ca].[typeProperties.source.storedProcedureParameters.settlementDate.value.value]
  , [ca].[typeProperties.source.type]
  , [ca].[typeProperties.stagingSettings.enableCompression]
  , [ca].[typeProperties.stagingSettings.linkedServiceName.referenceName]
  , [ca].[typeProperties.stagingSettings.linkedServiceName.type]
  , [ca].[typeProperties.stagingSettings.path]
  , [ca].[typeProperties.translator.mappings]
  , [ca].[typeProperties.translator.type]
  , [ca].[typeProperties.translator.typeConversion]
  , [ca].[typeProperties.translator.typeConversionSettings.allowDataTruncation]
  , [ca].[typeProperties.translator.typeConversionSettings.treatBooleanAsNumber]
  , [ca].[typeProperties.validateDataConsistency]
  , [ca].[userProperties]
  , [ip2].[parameters] AS [InputParameters]
  , [ip2].[referenceName] AS [InputReferenceName]
  , [ip2].[type] AS [InputType]
  , [ids].[DatasetType] AS [InputDatasetType]
  , [ids].[LinkedService] AS [InputDatasetLinkedService]
  , [ids].[Folder] AS [InputDatasetFolder]
  , [ids].[Description] AS [InputDatasetDescription]
  , [ids].[Schema] AS [InputDatasetSchema]
  , [ids].[Parameters] AS [InputDatasetParameters]
  , [ids].[Annotations] AS [InputDatasetAnnotations]
  , [ids].[TypeProperties] AS [InputDatasetTypeProperties]
  , [ids].[TargetTable] AS [InputDatasetTargetTable]
  , [ids].[TargetSchema] AS [InputDatasetTargetSchema]
  , [ids].[FileLocation] AS [InputDatasetFileLocation]
  , [ids].[FolderPath] AS [InputDatasetFolderPath]
  , [ids].[FileName] AS [InputDatasetFileName]
  , [op2].[parameters] AS [OutputParameters]
  , [op2].[referenceName] AS [OutputReferenceName]
  , [op2].[type] AS [OutputType]
  , [ods].[Dataset] AS [OutputDataset]
  , [ods].[DatasetType] AS [OutputDatasetType]
  , [ods].[LinkedService] AS [OutputDatasetLinkedService]
  , [ods].[Folder] AS [OutputDatasetFolder]
  , [ods].[Description] AS [OutputDatasetDescription]
  , [ods].[Schema] AS [OutputDatasetSchema]
  , [ods].[Parameters] AS [OutputDatasetParameters]
  , [ods].[Annotations] AS [OutputDatasetAnnotations]
  , [ods].[TypeProperties] AS [OutputDatasetTypeProperties]
  , [ods].[TargetTable] AS [OutputDatasetTargetTable]
  , [ods].[TargetSchema] AS [OutputDatasetTargetSchema]
  , [ods].[FileLocation] AS [OutputDatasetFileLocation]
  , [ods].[FolderPath] AS [OutputDatasetFolderPath]
  , [ods].[FileName] AS [OutputDatasetFileName]
INTO [##CopyActivities]
FROM [ADF].[CopyActivities] AS [ca]
OUTER APPLY OPENJSON([ca].[outputs]) AS [op]
OUTER APPLY OPENJSON([op].[value])
            WITH( [parameters] VARCHAR(MAX), [referenceName] VARCHAR(128), [type] VARCHAR(128)) AS [op2]
OUTER APPLY OPENJSON([ca].[inputs]) AS [ip]
OUTER APPLY OPENJSON([ip].[value])
            WITH( [parameters] VARCHAR(MAX), [referenceName] VARCHAR(128), [type] VARCHAR(128)) AS [ip2]
LEFT JOIN [ADF].[DataSets] AS [ids] ON [ip2].[referenceName] = [ids].[Dataset]
LEFT JOIN [ADF].[DataSets] AS [ods] ON [op2].[referenceName] = [ods].[Dataset]
LEFT JOIN [ADF].[TriggersDetailed] AS [td] ON [td].[PipelineName] = [ca].[PipelineName] ;

--WHERE [ods].[LinkedService] IN ('LS_SF_Application_DB', 'LS_SF_CONSOLIDATE', 'snowflake', 'SnowflakeDev') ;
CREATE CLUSTERED INDEX [CCI] ON [##CopyActivities]( [PipelineName], [CopyActivityName] ) ;
GO

SELECT
    [c].[IsDestinationSnowflake]
  , [c].[PipelineName]
  , [c].[CopyActivityName]
  , [TriggerName]
  , [TriggerType]
  , [TriggerRuntimeState]
  , [TriggerFrequency]
  , [TriggerStartTime]
  , [TriggerTimeZone]
  , [InputDatasetTargetSchema]
  , [InputDatasetTargetTable]
  , [OutputDatasetTargetSchema]
  , [OutputDatasetTargetTable]

  --, [c].[dependsOn]
  --, [c].[description]
  --, [c].[inputs]
  --, [c].[name]
  --, [c].[outputs]
  --, [c].[policy.retry]
  --, [c].[policy.retryIntervalInSeconds]
  --, [c].[policy.secureInput]
  --, [c].[policy.secureOutput]
  --, [c].[policy.timeout]
  --, [c].[type]
  --, [c].[typeProperties.dataIntegrationUnits]
  --, [c].[typeProperties.enableSkipIncompatibleRow]
  --, [c].[typeProperties.enableStaging]
  --, [c].[typeProperties.logSettings.copyActivityLogSettings.enableReliableLogging]
  --, [c].[typeProperties.logSettings.copyActivityLogSettings.logLevel]
  --, [c].[typeProperties.logSettings.enableCopyActivityLog]
  --, [c].[typeProperties.logSettings.logLocationSettings.linkedServiceName.referenceName]
  --, [c].[typeProperties.logSettings.logLocationSettings.linkedServiceName.type]
  --, [c].[typeProperties.logSettings.logLocationSettings.path]
  --, [c].[typeProperties.logStorageSettings.linkedServiceName.referenceName]
  --, [c].[typeProperties.logStorageSettings.linkedServiceName.type]
  --, [c].[typeProperties.logStorageSettings.path.type]
  --, [c].[typeProperties.logStorageSettings.path.value]
  --, [c].[typeProperties.parallelCopies]
  --, [c].[typeProperties.sink.allowCopyCommand]
  --, [c].[typeProperties.sink.allowPolyBase]
  --, [c].[typeProperties.sink.disableMetricsCollection]
  --, [c].[typeProperties.sink.formatSettings.fileExtension]
  --, [c].[typeProperties.sink.formatSettings.quoteAllText]
  --, [c].[typeProperties.sink.formatSettings.type]
  --, [c].[typeProperties.sink.importSettings.additionalCopyOptions.FORCE]
  --, [c].[typeProperties.sink.importSettings.additionalCopyOptions.ON_ERROR]
  --, [c].[typeProperties.sink.importSettings.type]
  --, [c].[typeProperties.sink.polyBaseSettings.rejectType]
  --, [c].[typeProperties.sink.polyBaseSettings.rejectValue]
  --, [c].[typeProperties.sink.polyBaseSettings.useTypeDefault]
  , [c].[typeProperties.sink.preCopyScript]
  , [c].[typeProperties.sink.preCopyScript.type]
  , [c].[typeProperties.sink.preCopyScript.value]

  --, [c].[typeProperties.sink.sqlWriterUseTableLock]
  --, [c].[typeProperties.sink.storeSettings.copyBehavior]
  --, [c].[typeProperties.sink.storeSettings.type]
  --, [c].[typeProperties.sink.tableOption]
  --, [c].[typeProperties.sink.type]
  --, [c].[typeProperties.sink.writeBatchSize]
  --, [c].[typeProperties.sink.writeBehavior]
  --, [c].[typeProperties.source.additionalColumns]
  --, [c].[typeProperties.source.exportSettings.type]
  --, [c].[typeProperties.source.formatSettings.compressionProperties.preserveZipFileNameAsFolder]
  --, [c].[typeProperties.source.formatSettings.compressionProperties.type]
  --, [c].[typeProperties.source.formatSettings.skipLineCount]
  --, [c].[typeProperties.source.formatSettings.type]
  --, [c].[typeProperties.source.isolationLevel]
  --, [c].[typeProperties.source.partitionOption]
  , [c].[typeProperties.source.query]
  , [c].[typeProperties.source.query.type]
  , [c].[typeProperties.source.query.value]

  --, [c].[typeProperties.source.queryTimeout]
  , [c].[typeProperties.source.sqlReaderQuery]
  , [c].[typeProperties.source.sqlReaderQuery.type]
  , [c].[typeProperties.source.sqlReaderQuery.value]
  , [c].[typeProperties.source.sqlReaderStoredProcedureName]

  --, [c].[typeProperties.source.storeSettings.deleteFilesAfterCompletion]
  --, [c].[typeProperties.source.storeSettings.enablePartitionDiscovery]
  --, [c].[typeProperties.source.storeSettings.recursive]
  --, [c].[typeProperties.source.storeSettings.type]
  --, [c].[typeProperties.source.storeSettings.wildcardFileName]
  --, [c].[typeProperties.source.storeSettings.wildcardFolderPath.type]
  --, [c].[typeProperties.source.storeSettings.wildcardFolderPath.value]
  --, [c].[typeProperties.source.storedProcedureParameters.CreateDate.type]
  --, [c].[typeProperties.source.storedProcedureParameters.CreateDate.value.type]
  --, [c].[typeProperties.source.storedProcedureParameters.CreateDate.value.value]
  --, [c].[typeProperties.source.storedProcedureParameters.reportDate.type]
  --, [c].[typeProperties.source.storedProcedureParameters.reportDate.value.type]
  --, [c].[typeProperties.source.storedProcedureParameters.reportDate.value.value]
  --, [c].[typeProperties.source.storedProcedureParameters.settlementDate.type]
  --, [c].[typeProperties.source.storedProcedureParameters.settlementDate.value.type]
  --, [c].[typeProperties.source.storedProcedureParameters.settlementDate.value.value]
  , [c].[typeProperties.source.type]

  --, [c].[typeProperties.stagingSettings.enableCompression]
  --, [c].[typeProperties.stagingSettings.linkedServiceName.referenceName]
  --, [c].[typeProperties.stagingSettings.linkedServiceName.type]
  --, [c].[typeProperties.stagingSettings.path]
  --, [c].[typeProperties.translator.mappings]
  --, [c].[typeProperties.translator.type]
  --, [c].[typeProperties.translator.typeConversion]
  --, [c].[typeProperties.translator.typeConversionSettings.allowDataTruncation]
  --, [c].[typeProperties.translator.typeConversionSettings.treatBooleanAsNumber]
  --, [c].[typeProperties.validateDataConsistency]
  --, [c].[userProperties]
  --, [InputParameters]
  , [InputReferenceName]
  --, [c].[InputType]
  , [InputDatasetType]
  , [InputDatasetLinkedService]
  , [InputDatasetFolder]
  , [c].[InputDatasetDescription]

  --, [InputDatasetSchema]
  --, [InputDatasetParameters]
  --, [InputDatasetAnnotations]
  --, [InputDatasetTypeProperties]

  --, [InputDatasetFileLocation]
  , [InputDatasetFolderPath]
  , [InputDatasetFileName]
  --, [OutputParameters]
  --, [OutputReferenceName]
  --, [c].[OutputType]
  , [OutputDataset]
  , [OutputDatasetType]
  , [OutputDatasetLinkedService]
  , [OutputDatasetFolder]
  , [c].[OutputDatasetDescription]
  --, [OutputDatasetSchema]
  --, [OutputDatasetParameters]
  --, [OutputDatasetAnnotations]
  --, [OutputDatasetTypeProperties]
  , [OutputDatasetFileLocation]
  , [OutputDatasetFolderPath]
  , [OutputDatasetFileName]
FROM [##CopyActivities] AS [c]
ORDER BY [c].[IsDestinationSnowflake] DESC
       , [c].[PipelineName]
       , [c].[CopyActivityName] ;

SELECT
    [ds].[Dataset]
  , [ds].[DatasetType]
  , [ds].[LinkedService]
  , [ds].[Folder]
  , [ds].[Description]
  , [ds].[Schema]
  , [ds].[Parameters]
  , [ds].[Annotations]
  , [ds].[TypeProperties]
  , [ds].[TargetTable]
  , [ds].[TargetSchema]
  , [ds].[FileLocation]
  , [ds].[FolderPath]
  , [ds].[FileName]
FROM [ADF].[DataSets] AS [ds] ;

SELECT
    [dd].[DataFlow]
  , [dd].[Type]
  , [dd].[DependencyType]
  , [dd].[DependencyName]
FROM [ADF].[DataFlowDependencies] AS [dd] ;

SELECT
    [p].[Pipeline]
  , [p].[PipelineActivityCnt]
  , [p].[ParameterCnt]
  , [p].[ParameterWithValueCnt]
  , [p].[DependsOnCnt]
FROM [ADF].[PipeLines] AS [p] ;

SELECT
    [p].[Pipeline]
  , [p].[PipelineActivitiesCnt]
  , [p].[Level]
  , [p].[ChildrenCnt]
  , [p].[ParentId]
  , [p].[Id]
  , [p].[Activity]
  , [p].[ActivityType]
  , [p].[ParentActivity]
  , [p].[ParentActivityType]
  , [p].[SwitchExpressionValue]
  , [p].[SwitchExpressionType]
  , [p].[IFExpressionValue]
  , [p].[IFExpressionType]
  , [p].[SwitchValue]
  , [p].[IFCondition]
FROM [ADF].[PipeLineActivities] AS [p] ;

SELECT
    [p].[Pipeline]
  , [p].[ActivityName]
  , [p].[ActivityType]
  , [p].[Level]
  , [p].[ActivityId]
  , [p].[ActivityValue]
FROM [ADF].[PipeLineAllActivities] AS [p] ;

SELECT
    [t].[Pipeline]
  , [t].[Activity]
  , [t].[ActivityType]
  , [t].[QueryId]
  , [t].[Query]
  , [t].[Type]
FROM [ADF].[SQLQueries] AS [t] ;

SELECT
    [q].[Pipeline]
  , [q].[Activity]
  , [q].[ActivityType]
  , [q].[ActivityId]
  , [q].[Query]
FROM [ADF].[ActivityQueries] AS [q] ;

SELECT
    [pd].[Pipeline]
  , [pd].[DependsOnType]
  , [pd].[DependsOnName]
FROM [ADF].[PipeLineDependencies] AS [pd] ;

SELECT
    [t].[TriggerName]
  , [t].[RunTimeState]
  , [t].[PipeLineCnt]
  , [t].[PipeLines]
  , [t].[TriggerType]
  , [t].[Frequency]
  , [t].[Interval]
  , [t].[StartTime]
  , [t].[TimeZone]
FROM [ADF].[Triggers] AS [t] ;

SELECT
    [tt].[TriggerName]
  , [tt].[RunTimeState]
  , [tt].[ScheduleTimeCnt]
  , [tt].[ScheduleTimeId]
  , [tt].[TriggerType]
  , [tt].[Frequency]
  , [tt].[Interval]
  , [tt].[StartTime]
  , [tt].[TimeZone]
  , [tt].[ScheduleTime]
FROM [ADF].[TriggerTimes] AS [tt] ;

SELECT
    [tp].[TriggerName]
  , [tp].[RunTimeState]
  , [tp].[ParameterCnt]
  , [tp].[ParameterName]
  , [tp].[ParameterType]
  , [tp].[ParameterDefaultValue]
FROM [ADF].[TriggerParameters] AS [tp] ;

SELECT
    [tpl].[TriggerName]
  , [tpl].[RunTimeState]
  , [tpl].[PipeLineCnt]
  , [tpl].[PipeLine]
FROM [ADF].[TriggerPipeLines] AS [tpl] ;

SELECT
    [t].[Pipeline]
  , [t].[StoredProcedureName]
  , [t].[StoredProcedureId]
  , [t].[ActivityTypeList]
  , [t].[StoredProcedureCnt]
  , [t].[StoredProcedureParamCnt]
  , [t].[StoredProcedureParamNotNullCnt]
FROM [ADF].[StoredProcedureOrLookup] AS [t] ;

SELECT
    [t].[Pipeline]
  , [t].[Activity]
  , [t].[ActivityType]
  , [t].[StoredProcedureName]
  , [t].[StoredProcedureId]
  , [t].[StoredProcedureParamId]
  , [t].[ParameterName]
  , [t].[ParameterDataType]
  , [t].[ParameterType]
  , [t].[ParameterValue]
FROM [ADF].[StoredProcedureOrLookupParameters] AS [t] ;

SELECT
    [a].[Pipeline]
  , [a].[ActivityName]
  , [a].[Level]
  , [a].[ActivityType]
  , [a].[InputOrOutput]
  , [a].[InputOutputId]
  , [a].[ReferenceName]
  , [a].[ReferenceType]
  , [a].[LinkedService]
  , [a].[ReferenceValue]
FROM [ADF].[ActivityReferences] AS [a]
ORDER BY [a].[Pipeline]
       , [a].[ActivityName]
       , [a].[InputOrOutput]
       , [a].[InputOutputId] ;
