CREATE OR REPLACE TEMPORARY TABLE TEMP(TABLE_CATALOG VARCHAR(128), TABLE_SCHEMA VARCHAR(128), TABLE_NAME VARCHAR(128), COLUMN_NAME VARCHAR(128), COLUMN_VALUE TIMESTAMP_NTZ, ROW_COUNT BIGINT);

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'AccountSystemEntryDate' AS COLUMN_NAME, AccountSystemEntryDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY AccountSystemEntryDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'BirthDate' AS COLUMN_NAME, BirthDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY BirthDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'CardStatusChangeDate' AS COLUMN_NAME, CardStatusChangeDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY CardStatusChangeDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'CreateDate' AS COLUMN_NAME, CreateDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY CreateDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'ExpirationDate' AS COLUMN_NAME, ExpirationDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY ExpirationDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'ModifiedDate' AS COLUMN_NAME, ModifiedDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY ModifiedDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'ReportDate' AS COLUMN_NAME, ReportDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY ReportDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolderEmail' AS TABLE_NAME, 'CreateDate' AS COLUMN_NAME, CreateDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolderEmail
GROUP BY CreateDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolderEmail' AS TABLE_NAME, 'ModifiedDate' AS COLUMN_NAME, ModifiedDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolderEmail
GROUP BY ModifiedDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolderEmail' AS TABLE_NAME, 'ReportDate' AS COLUMN_NAME, ReportDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolderEmail
GROUP BY ReportDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'transactions_log' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".transactions_log
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'avg_daily_revenue_begin_date' AS COLUMN_NAME, avg_daily_revenue_begin_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY avg_daily_revenue_begin_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'begin_dts' AS COLUMN_NAME, begin_dts AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY begin_dts;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'end_dts' AS COLUMN_NAME, end_dts AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY end_dts;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'fscl_day_dts' AS COLUMN_NAME, fscl_day_dts AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY fscl_day_dts;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'fscl_half_year_dts' AS COLUMN_NAME, fscl_half_year_dts AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY fscl_half_year_dts;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'fscl_month_dts' AS COLUMN_NAME, fscl_month_dts AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY fscl_month_dts;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'fscl_qtr_dts' AS COLUMN_NAME, fscl_qtr_dts AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY fscl_qtr_dts;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'fscl_week_dts' AS COLUMN_NAME, fscl_week_dts AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY fscl_week_dts;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'fscl_year_dts' AS COLUMN_NAME, fscl_year_dts AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY fscl_year_dts;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'last_friday_dt' AS COLUMN_NAME, last_friday_dt AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY last_friday_dt;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'month_begin_dt' AS COLUMN_NAME, month_begin_dt AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY month_begin_dt;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'month_end_dt' AS COLUMN_NAME, month_end_dt AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY month_end_dt;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'prev_day_dt' AS COLUMN_NAME, prev_day_dt AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY prev_day_dt;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'same_day_year_ago' AS COLUMN_NAME, same_day_year_ago AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY same_day_year_ago;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'tomorrow_dt' AS COLUMN_NAME, tomorrow_dt AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY tomorrow_dt;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date' AS TABLE_NAME, 'week_ending_dt' AS COLUMN_NAME, week_ending_dt AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date
GROUP BY week_ending_dt;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date_dashboard' AS TABLE_NAME, 'date_end' AS COLUMN_NAME, date_end AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date_dashboard
GROUP BY date_end;

INSERT INTO TEMP
SELECT 'CONSOLIDATE' AS TABLE_CATALOG, 'COMMON' AS TABLE_SCHEMA, 'dim_date_dashboard' AS TABLE_NAME, 'date_end' AS COLUMN_NAME, date_end AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "CONSOLIDATE"."COMMON".dim_date_dashboard
GROUP BY date_end;

INSERT INTO TEMP
SELECT 'CONSOLIDATE' AS TABLE_CATALOG, 'COMMON' AS TABLE_SCHEMA, 'dim_date_dashboard' AS TABLE_NAME, 'date_end_prev' AS COLUMN_NAME, date_end_prev AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "CONSOLIDATE"."COMMON".dim_date_dashboard
GROUP BY date_end_prev;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date_dashboard' AS TABLE_NAME, 'date_end_prev' AS COLUMN_NAME, date_end_prev AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date_dashboard
GROUP BY date_end_prev;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date_dashboard' AS TABLE_NAME, 'date_start' AS COLUMN_NAME, date_start AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date_dashboard
GROUP BY date_start;

INSERT INTO TEMP
SELECT 'CONSOLIDATE' AS TABLE_CATALOG, 'COMMON' AS TABLE_SCHEMA, 'dim_date_dashboard' AS TABLE_NAME, 'date_start' AS COLUMN_NAME, date_start AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "CONSOLIDATE"."COMMON".dim_date_dashboard
GROUP BY date_start;

INSERT INTO TEMP
SELECT 'CONSOLIDATE' AS TABLE_CATALOG, 'COMMON' AS TABLE_SCHEMA, 'dim_date_dashboard' AS TABLE_NAME, 'date_start_prev' AS COLUMN_NAME, date_start_prev AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "CONSOLIDATE"."COMMON".dim_date_dashboard
GROUP BY date_start_prev;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_date_dashboard' AS TABLE_NAME, 'date_start_prev' AS COLUMN_NAME, date_start_prev AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_date_dashboard
GROUP BY date_start_prev;

INSERT INTO TEMP
SELECT 'CONSOLIDATE' AS TABLE_CATALOG, 'FINANCIALINSTITUTION' AS TABLE_SCHEMA, 'dim_client' AS TABLE_NAME, 'begin_effective_date' AS COLUMN_NAME, begin_effective_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "CONSOLIDATE"."FINANCIALINSTITUTION".dim_client
GROUP BY begin_effective_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_client' AS TABLE_NAME, 'begin_effective_date' AS COLUMN_NAME, begin_effective_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_client
GROUP BY begin_effective_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_client' AS TABLE_NAME, 'end_effective_date' AS COLUMN_NAME, end_effective_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_client
GROUP BY end_effective_date;

INSERT INTO TEMP
SELECT 'CONSOLIDATE' AS TABLE_CATALOG, 'FINANCIALINSTITUTION' AS TABLE_SCHEMA, 'dim_client' AS TABLE_NAME, 'end_effective_date' AS COLUMN_NAME, end_effective_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "CONSOLIDATE"."FINANCIALINSTITUTION".dim_client
GROUP BY end_effective_date;

INSERT INTO TEMP
SELECT 'CONSOLIDATE' AS TABLE_CATALOG, 'FINANCIALINSTITUTION' AS TABLE_SCHEMA, 'dim_client' AS TABLE_NAME, 'MERGER_ACQUISITION_DTE' AS COLUMN_NAME, MERGER_ACQUISITION_DTE AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "CONSOLIDATE"."FINANCIALINSTITUTION".dim_client
GROUP BY MERGER_ACQUISITION_DTE;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_client' AS TABLE_NAME, 'MERGER_ACQUISITION_DTE' AS COLUMN_NAME, MERGER_ACQUISITION_DTE AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_client
GROUP BY MERGER_ACQUISITION_DTE;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'AccountMisc' AS TABLE_NAME, 'CreateDate' AS COLUMN_NAME, CreateDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".AccountMisc
GROUP BY CreateDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'AccountMisc' AS TABLE_NAME, 'ModifiedDate' AS COLUMN_NAME, ModifiedDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".AccountMisc
GROUP BY ModifiedDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'AccountMisc' AS TABLE_NAME, 'ReportDate' AS COLUMN_NAME, ReportDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".AccountMisc
GROUP BY ReportDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'AccountSystemEntryDate' AS COLUMN_NAME, AccountSystemEntryDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY AccountSystemEntryDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'BirthDate' AS COLUMN_NAME, BirthDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY BirthDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'CardStatusChangeDate' AS COLUMN_NAME, CardStatusChangeDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY CardStatusChangeDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'CreateDate' AS COLUMN_NAME, CreateDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY CreateDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'ExpirationDate' AS COLUMN_NAME, ExpirationDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY ExpirationDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'ModifiedDate' AS COLUMN_NAME, ModifiedDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY ModifiedDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'ReportDate' AS COLUMN_NAME, ReportDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY ReportDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolderEmail' AS TABLE_NAME, 'CreateDate' AS COLUMN_NAME, CreateDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolderEmail
GROUP BY CreateDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolderEmail' AS TABLE_NAME, 'ModifiedDate' AS COLUMN_NAME, ModifiedDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolderEmail
GROUP BY ModifiedDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolderEmail' AS TABLE_NAME, 'ReportDate' AS COLUMN_NAME, ReportDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolderEmail
GROUP BY ReportDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'dim_account' AS TABLE_NAME, 'account_activation_date' AS COLUMN_NAME, account_activation_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".dim_account
GROUP BY account_activation_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'dim_account' AS TABLE_NAME, 'account_closed_date' AS COLUMN_NAME, account_closed_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".dim_account
GROUP BY account_closed_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'dim_account' AS TABLE_NAME, 'account_delinquent_date' AS COLUMN_NAME, account_delinquent_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".dim_account
GROUP BY account_delinquent_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'dim_account' AS TABLE_NAME, 'account_expiration_date' AS COLUMN_NAME, account_expiration_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".dim_account
GROUP BY account_expiration_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'dim_account' AS TABLE_NAME, 'account_issue_date' AS COLUMN_NAME, account_issue_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".dim_account
GROUP BY account_issue_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'dim_account' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".dim_account
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'dim_account' AS TABLE_NAME, 'first_txn_date' AS COLUMN_NAME, first_txn_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".dim_account
GROUP BY first_txn_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'dim_account' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".dim_account
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'dim_account' AS TABLE_NAME, 'modified_date' AS COLUMN_NAME, modified_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".dim_account
GROUP BY modified_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'Person' AS TABLE_NAME, 'BirthDate' AS COLUMN_NAME, BirthDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".Person
GROUP BY BirthDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'Person' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".Person
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'Person' AS TABLE_NAME, 'modified_date' AS COLUMN_NAME, modified_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".Person
GROUP BY modified_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_merchant' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_merchant
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_merchant' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_merchant
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_merchant_terminal_geography' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_merchant_terminal_geography
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_merchant_terminal_geography' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_merchant_terminal_geography
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_merchant_type' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_merchant_type
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'SMARTGROWTH' AS TABLE_SCHEMA, 'dim_merchant_type' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."SMARTGROWTH".dim_merchant_type
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'SMARTGROWTH' AS TABLE_SCHEMA, 'dim_merchant_type' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."SMARTGROWTH".dim_merchant_type
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_merchant_type' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_merchant_type
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'APPLICATION_DB' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'map_status' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "APPLICATION_DB"."REWARDS".map_status
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'map_transaction_type' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".map_transaction_type
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'map_wallet_payment_token_requestor' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".map_wallet_payment_token_requestor
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'member_response_daily_error' AS TABLE_NAME, 'DOB_Date' AS COLUMN_NAME, DOB_Date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".member_response_daily_error
GROUP BY DOB_Date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'member_response_daily_error' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".member_response_daily_error
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'MemberDemographic' AS TABLE_NAME, 'AnniversaryDate' AS COLUMN_NAME, AnniversaryDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".MemberDemographic
GROUP BY AnniversaryDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'MemberDemographic' AS TABLE_NAME, 'BirthDate' AS COLUMN_NAME, BirthDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".MemberDemographic
GROUP BY BirthDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'MemberTransaction' AS TABLE_NAME, 'TRANSACTION_DTM' AS COLUMN_NAME, TRANSACTION_DTM AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".MemberTransaction
GROUP BY TRANSACTION_DTM;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'user_mapping' AS TABLE_NAME, 'Load_Date' AS COLUMN_NAME, Load_Date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".user_mapping
GROUP BY Load_Date;

INSERT INTO TEMP
SELECT 'APPLICATION_DB' AS TABLE_CATALOG, 'SHAREDBRANCH' AS TABLE_SCHEMA, 'CUSC_acquirer' AS TABLE_NAME, 'closing_date' AS COLUMN_NAME, closing_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "APPLICATION_DB"."SHAREDBRANCH".CUSC_acquirer
GROUP BY closing_date;

INSERT INTO TEMP
SELECT 'APPLICATION_DB' AS TABLE_CATALOG, 'SHAREDBRANCH' AS TABLE_SCHEMA, 'CUSC_acquirer' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "APPLICATION_DB"."SHAREDBRANCH".CUSC_acquirer
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'APPLICATION_DB' AS TABLE_CATALOG, 'SHAREDBRANCH' AS TABLE_SCHEMA, 'CUSC_issuer' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "APPLICATION_DB"."SHAREDBRANCH".CUSC_issuer
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'SHAREDBRANCH' AS TABLE_SCHEMA, 'dim_business_partner' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."SHAREDBRANCH".dim_business_partner
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'AccountMisc' AS TABLE_NAME, 'ModifiedDate' AS COLUMN_NAME, ModifiedDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".AccountMisc
GROUP BY ModifiedDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'AccountSystemEntryDate' AS COLUMN_NAME, AccountSystemEntryDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY AccountSystemEntryDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'BirthDate' AS COLUMN_NAME, BirthDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY BirthDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'CardStatusChangeDate' AS COLUMN_NAME, CardStatusChangeDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY CardStatusChangeDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'CreateDate' AS COLUMN_NAME, CreateDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY CreateDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'ExpirationDate' AS COLUMN_NAME, ExpirationDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY ExpirationDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'ModifiedDate' AS COLUMN_NAME, ModifiedDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY ModifiedDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolder' AS TABLE_NAME, 'ReportDate' AS COLUMN_NAME, ReportDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolder
GROUP BY ReportDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolderEmail' AS TABLE_NAME, 'CreateDate' AS COLUMN_NAME, CreateDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolderEmail
GROUP BY CreateDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolderEmail' AS TABLE_NAME, 'ModifiedDate' AS COLUMN_NAME, ModifiedDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolderEmail
GROUP BY ModifiedDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'DEMOGRAPHICS' AS TABLE_SCHEMA, 'CardHolderEmail' AS TABLE_NAME, 'ReportDate' AS COLUMN_NAME, ReportDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."DEMOGRAPHICS".CardHolderEmail
GROUP BY ReportDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'MemberDemographic' AS TABLE_NAME, 'AnniversaryDate' AS COLUMN_NAME, AnniversaryDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".MemberDemographic
GROUP BY AnniversaryDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'MemberDemographic' AS TABLE_NAME, 'BirthDate' AS COLUMN_NAME, BirthDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".MemberDemographic
GROUP BY BirthDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'rewards_outbound_transaction_split_1' AS TABLE_NAME, 'endDate' AS COLUMN_NAME, endDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".rewards_outbound_transaction_split_1
GROUP BY endDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'rewards_outbound_transaction_split_1' AS TABLE_NAME, 'postDate' AS COLUMN_NAME, postDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".rewards_outbound_transaction_split_1
GROUP BY postDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REWARDS' AS TABLE_SCHEMA, 'rewards_outbound_transaction_split_1' AS TABLE_NAME, 'startDate' AS COLUMN_NAME, startDate AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REWARDS".rewards_outbound_transaction_split_1
GROUP BY startDate;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_card_entry_method' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_card_entry_method
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_card_entry_method' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_card_entry_method
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_network' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_network
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_network' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_network
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_payment_token_requestor' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_payment_token_requestor
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_payment_token_requestor' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_payment_token_requestor
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_response_code' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_response_code
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_response_code' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_response_code
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_terminal' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_terminal
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_terminal' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_terminal
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'REFERENCE' AS TABLE_SCHEMA, 'dim_terminal' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."REFERENCE".dim_terminal
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_terminal' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_terminal
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_transaction_name' AS TABLE_NAME, 'create_date' AS COLUMN_NAME, create_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_transaction_name
GROUP BY create_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'dim_transaction_name' AS TABLE_NAME, 'load_date' AS COLUMN_NAME, load_date AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".dim_transaction_name
GROUP BY load_date;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'fact_transaction' AS TABLE_NAME, 'import_file_date_key' AS COLUMN_NAME, import_file_date_key AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".fact_transaction
GROUP BY import_file_date_key;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'fact_transaction' AS TABLE_NAME, 'origin_date_key' AS COLUMN_NAME, origin_date_key AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".fact_transaction
GROUP BY origin_date_key;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'fact_transaction' AS TABLE_NAME, 'settlement_date_key' AS COLUMN_NAME, settlement_date_key AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".fact_transaction
GROUP BY settlement_date_key;

INSERT INTO TEMP
SELECT 'EDW' AS TABLE_CATALOG, 'TRANSACTION' AS TABLE_SCHEMA, 'fact_transaction' AS TABLE_NAME, 'transmission_date_key' AS COLUMN_NAME, transmission_date_key AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM "EDW"."TRANSACTION".fact_transaction
GROUP BY transmission_date_key;


SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_VALUE, ROW_COUNT
FROM TEMP
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME;