USE [Velera] ;
GO
DROP TABLE IF EXISTS [#CommonColumns] ;

SELECT
    [c].[TABLE_SCHEMA]
  , [c].[TABLE_NAME]
  , [c].[COLUMN_NAME]
  , [c].[DATA_TYPE]
  , MAX([c].[ORDINAL_POSITION]) AS [max_ordinal_position]
INTO [#CommonColumns]
FROM [dbo].[SnowflakeColumns] [s]
INNER JOIN [dbo].[SQLColumns] [c] ON [s].[TABLE_NAME] = [c].[TABLE_NAME] AND [s].[COLUMN_NAME] = [c].[COLUMN_NAME]
WHERE [s].[DATA_TYPE] IN ('TIMESTAMP_LTZ', 'DATE', 'TIMESTAMP_NTZ') AND [c].[DATA_TYPE] IN ('date', 'datetime', 'datetime2')
GROUP BY [c].[TABLE_SCHEMA]
       , [c].[TABLE_NAME]
       , [c].[COLUMN_NAME]
       , [c].[DATA_TYPE] ;

DROP TABLE IF EXISTS [ColumnMatches_2] ;

SELECT
    [t].[schema_name] AS [SQL_TABLE_SCHEMA]
  , [r].[SF_TABLE_CATALOG]
  , [r].[SF_TABLE_SCHEMA]
  , [t].[object_name] AS [TABLE_NAME]
  , [t].[type_desc]
  , [t].[rows] AS [SQL_ROW_COUNT]
  , [r].[SF_ROW_COUNT]
  , [t].[create_date]
  , [t].[modify_date]
  , [mc].[COLUMN_NAME]
  , [mc].[DATA_TYPE]
INTO [ColumnMatches_2]
FROM [dbo].[SQLTables] [t]
INNER JOIN [#CommonColumns] [mc] ON [mc].[TABLE_SCHEMA] = [t].[schema_name] AND [mc].[TABLE_NAME] = [t].[object_name]
LEFT JOIN [dbo].[Comparison_2] [r] ON [r].[Missing] IS NULL AND [r].[SQL_TABLE_SCHEMA] = [t].[schema_name] AND [r].[TABLE_NAME] = [t].[object_name]
WHERE [t].[rows] IS NOT NULL AND [r].[SQL_TABLE_SCHEMA] IS NOT NULL
ORDER BY [t].[schema_name]
       , [t].[object_name] ;

CREATE UNIQUE CLUSTERED INDEX [CCI] ON [ColumnMatches_2]( [SQL_TABLE_SCHEMA], [SF_TABLE_SCHEMA], [TABLE_NAME], [COLUMN_NAME] ) ;

-- SQL POOL
SELECT 'CREATE TABLE #TEMP([TABLE_SCHEMA] VARCHAR(128), [TABLE_NAME] VARCHAR(128), [COLUMN_NAME] VARCHAR(128), [COLUMN_VALUE] DATETIME2(3), [ROW_COUNT] BIGINT);

'   AS [SQL]
UNION ALL
SELECT CONCAT('INSERT INTO #TEMP
SELECT ''', [A].[SQL_TABLE_SCHEMA], ''' AS [TABLE_SCHEMA], ''', [A].[TABLE_NAME], ''' AS [TABLE_NAME], ''', [A].[COLUMN_NAME], ''' AS [COLUMN_NAME], ', QUOTENAME([A].[COLUMN_NAME]), ' AS [COLUMN_VALUE], COUNT_BIG(1) AS [ROW_COUNT]
FROM ', QUOTENAME([A].[SQL_TABLE_SCHEMA]), '.', QUOTENAME([A].[TABLE_NAME]), '
GROUP BY ', QUOTENAME([A].[COLUMN_NAME]), ';

')  AS [SQL]
FROM( SELECT TOP 999999 * FROM [dbo].[ColumnMatches_2] ORDER BY [SQL_TABLE_SCHEMA], [TABLE_NAME], [COLUMN_NAME] ) [A]
UNION ALL
SELECT '
SELECT [TABLE_SCHEMA], [TABLE_NAME], [COLUMN_NAME], [COLUMN_VALUE], [ROW_COUNT]
FROM #TEMP
ORDER BY [TABLE_SCHEMA], [TABLE_NAME];' AS [SQL] ;

-- SNOWFLAKE
SELECT 'CREATE OR REPLACE TEMPORARY TABLE TEMP(TABLE_CATALOG VARCHAR(128), TABLE_SCHEMA VARCHAR(128), TABLE_NAME VARCHAR(128), COLUMN_NAME VARCHAR(128), COLUMN_VALUE TIMESTAMP_NTZ, ROW_COUNT BIGINT);

'   AS [SQL]
UNION ALL
SELECT CONCAT('INSERT INTO TEMP
SELECT ''', [A].[SF_TABLE_CATALOG], ''' AS TABLE_CATALOG, ''', [A].[SF_TABLE_SCHEMA], ''' AS TABLE_SCHEMA, ''', [A].[TABLE_NAME], ''' AS TABLE_NAME, ''', [A].[COLUMN_NAME], ''' AS COLUMN_NAME, ', [A].[COLUMN_NAME], ' AS COLUMN_VALUE, COUNT(1) AS ROW_COUNT
FROM ', QUOTENAME([A].[SF_TABLE_CATALOG], '"'), '.', QUOTENAME([A].[SF_TABLE_SCHEMA], '"'), '.', [A].[TABLE_NAME], '
GROUP BY ', [A].[COLUMN_NAME], ';

')  AS [SQL]
FROM( SELECT TOP 999999 * FROM [dbo].[ColumnMatches_2] ORDER BY [SQL_TABLE_SCHEMA], [TABLE_NAME], [COLUMN_NAME] ) [A]
UNION ALL
SELECT '
SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_VALUE, ROW_COUNT
FROM TEMP
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME;' AS [SQL] ;
