SELECT
	TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_OWNER, TABLE_TYPE, IS_TRANSIENT, ROW_COUNT, BYTES, RETENTION_TIME, CREATED, LAST_ALTERED, LAST_DDL, LAST_DDL_BY, COMMENT, IS_TEMPORARY, IS_ICEBERG, IS_DYNAMIC
FROM CONSOLIDATE.INFORMATION_SCHEMA.TABLES
UNION ALL
SELECT
	TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_OWNER, TABLE_TYPE, IS_TRANSIENT, ROW_COUNT, BYTES, RETENTION_TIME, CREATED, LAST_ALTERED, LAST_DDL, LAST_DDL_BY, COMMENT, IS_TEMPORARY, IS_ICEBERG, IS_DYNAMIC
FROM EDW.INFORMATION_SCHEMATABLES
UNION ALL
SELECT
	TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_OWNER, TABLE_TYPE, IS_TRANSIENT, ROW_COUNT, BYTES, RETENTION_TIME, CREATED, LAST_ALTERED, LAST_DDL, LAST_DDL_BY, COMMENT, IS_TEMPORARY, IS_ICEBERG, IS_DYNAMIC
FROM APPLICATION_DB.INFORMATION_SCHEMA.TABLES



SELECT
	TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, COLUMN_DEFAULT, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, CHARACTER_OCTET_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, DATETIME_PRECISION, IS_IDENTITY, IDENTITY_START, IDENTITY_INCREMENT, COMMENT
FROM CONSOLIDATE.INFORMATION_SCHEMA.COLUMNS
UNION ALL
SELECT
	TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, COLUMN_DEFAULT, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, CHARACTER_OCTET_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, DATETIME_PRECISION, IS_IDENTITY, IDENTITY_START, IDENTITY_INCREMENT, COMMENT
FROM EDW.INFORMATION_SCHEMA.COLUMNS
UNION ALL
SELECT
	TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, COLUMN_DEFAULT, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, CHARACTER_OCTET_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, DATETIME_PRECISION, IS_IDENTITY, IDENTITY_START, IDENTITY_INCREMENT, COMMENT
FROM APPLICATION_DB.INFORMATION_SCHEMA.COLUMNS

SELECT
    s.name AS schema_name
  , o.name
  , o.parent_object_id
  , o.type
  , o.type_desc
  , p.rows
  , o.create_date
  , o.modify_date
FROM sys.objects o
INNER JOIN sys.schemas s ON s.schema_id = o.schema_id
LEFT JOIN( SELECT p.object_id, SUM(p.rows) AS rows FROM sys.partitions p GROUP BY p.object_id ) p ON p.object_id = o.object_id ;

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS ;
